<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Unrecoverable exceptions | Elasticsearch.Net and NEST: the .NET clients [5.x] | Elastic</title>
<meta class="elastic" name="content" content="Unrecoverable exceptions | Elasticsearch.Net and NEST: the .NET clients [5.x]">

<link rel="home" href="index.html" title="Elasticsearch.Net and NEST: the .NET clients [5.x]"/>
<link rel="up" href="thrown-exceptions.html" title="Exceptions"/>
<link rel="prev" href="unexpected-exceptions.html" title="Unexpected exceptions"/>
<link rel="next" href="transports-and-pipelines.html" title="Transports and pipelines"/>
<meta class="elastic" name="product_version" content="5.x"/>
<meta class="elastic" name="product_name" content="Clients"/>
<meta class="elastic" name="website_area" content="documentation"/>
<meta name="DC.type" content="Learn/Docs/Clients/.Net/5.x"/>
<meta name="DC.subject" content="Clients"/>
<meta name="DC.identifier" content="5.x"/>
</head>
<body>
<div class="page_header">
<p>
  <strong>WARNING</strong>: Version 5.x has passed its 
  <a href="https://www.elastic.co/support/eol">EOL date</a>. 
</p>  
<p>
  This documentation is no longer being maintained and may be removed. 
  If you are running this version, we strongly advise you to upgrade. 
  For the latest information, see the 
  <a href="../current/index.html">current release documentation</a>. 
</p>
</div>
<div class="navheader">
<span class="prev">
<a href="unexpected-exceptions.html">« Unexpected exceptions</a>
</span>
<span class="next">
<a href="transports-and-pipelines.html">Transports and pipelines »</a>
</span>
</div>
<div class="book" lang="en">
<div class="titlepage">
<div class="breadcrumbs">
<span class="breadcrumb-link"><a href="/guide/">Elastic Docs</a></span>
<span class="chevron-right">›</span><span class="breadcrumb-link"><a href="index.html">Elasticsearch.Net and NEST:  the .NET clients [5.x]</a></span>
<span class="chevron-right">›</span><span class="breadcrumb-link"><a href="api-conventions.html">API Conventions</a></span>
<span class="chevron-right">›</span><span class="breadcrumb-link"><a href="thrown-exceptions.html">Exceptions</a></span>
</div>
<div>
<div><h1 class="title"><a id="id-1"></a>Unrecoverable exceptions</h1><a class="edit_me" rel="nofollow" title="Edit this page on GitHub" href="https://github.com/elastic/elasticsearch-net/edit/5.x/docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc">edit</a></div>
</div>
<!--EXTRA-->
</div>
<div id="content">
<div class="section">
<div class="titlepage"><div><div>
<h2 class="title"><a id="unrecoverable-exceptions"></a>Unrecoverable exceptions<a class="edit_me" rel="nofollow" title="Edit this page on GitHub" href="https://github.com/elastic/elasticsearch-net/edit/5.x/docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc">edit</a></h2>
</div></div></div>
<p>Unrecoverable exceptions are <em>expected</em> exceptions that are grounds to exit the client pipeline immediately.</p>
<div class="note admon">
<div class="icon"></div>
<div class="admon_content">
<p>What do we mean by <em>expected</em> exceptions? Aren&#8217;t all exceptions <em>exceptional</em>?</p>
<p>Well, there a some exceptions that can be thrown in the course of a request
that <em>may</em> be expected, some of which can be retried on another node in the cluster, and some that cannot.
For example, an exception thrown when pinging a node throws an exception,
but this is an exception that the client expects can happen,
and can handle by trying a ping on another node. On the contrary, a bad authentication response from a node will throw an
exception, and the client understands that an exception under these circumstances should be handled by not retrying,
but by exiting the pipeline.</p>
</div>
</div>
<p>By default, the client won&#8217;t throw on any <code class="literal">ElasticsearchClientException</code> but instead return an invalid response
that can be detected by checking the <code class="literal">.IsValid</code> property on the response. You can change this behaviour with
by using <code class="literal">ThrowExceptions()</code> on <a class="xref" href="configuration-options.html" title="Configuration options"><code class="literal">ConnectionSettings</code></a>.</p>
<p>The following is a collection of unrecoverable exceptions</p>
<div class="pre_wrapper lang-csharp">
<div class="console_code_copy" title="Copy to clipboard"></div>
<pre class="programlisting prettyprint lang-csharp">var unrecoverableExceptions = new[]
{
    new PipelineException(PipelineFailure.CouldNotStartSniffOnStartup),
    new PipelineException(PipelineFailure.SniffFailure),
    new PipelineException(PipelineFailure.Unexpected),
    new PipelineException(PipelineFailure.BadAuthentication),
    new PipelineException(PipelineFailure.MaxRetriesReached),
    new PipelineException(PipelineFailure.MaxTimeoutReached)
};

unrecoverableExceptions.Should().OnlyContain(e =&gt; !e.Recoverable);</pre>
</div>
<p>As an example, let&#8217;s use our Virtual cluster test framework to set up a 10 node cluster
that always succeeds when pinged but fails with a 401 response when making client calls</p>
<div class="pre_wrapper lang-csharp">
<div class="console_code_copy" title="Copy to clipboard"></div>
<pre class="programlisting prettyprint lang-csharp">var audit = new Auditor(() =&gt; Framework.Cluster
    .Nodes(10)
    .Ping(r =&gt; r.SucceedAlways()) <a id="CO5-1"></a><i class="conum" data-value="1"></i>
    .ClientCalls(r =&gt; r.FailAlways(401)) <a id="CO5-2"></a><i class="conum" data-value="2"></i>
    .StaticConnectionPool()
    .AllDefaults()
);</pre>
</div>
<div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO5-1"><i class="conum" data-value="1"></i></a></p>
</td>
<td align="left" valign="top">
<p>Always succeed on ping</p>
</td>
</tr>
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO5-2"><i class="conum" data-value="2"></i></a></p>
</td>
<td align="left" valign="top">
<p>&#8230;&#8203;but always fail on calls with a 401 Bad Authentication response</p>
</td>
</tr>
</table>
</div>
<p>Now, let&#8217;s make a client call. We&#8217;ll see that the first audit event is a successful ping
followed by a bad response as a result of the 401 bad authentication response</p>
<div class="pre_wrapper lang-csharp">
<div class="console_code_copy" title="Copy to clipboard"></div>
<pre class="programlisting prettyprint lang-csharp">audit = await audit.TraceElasticsearchException(
    new ClientCall {
        { AuditEvent.PingSuccess, 9200 }, <a id="CO6-1"></a><i class="conum" data-value="1"></i>
        { AuditEvent.BadResponse, 9200 }, <a id="CO6-2"></a><i class="conum" data-value="2"></i>
    },
    exception =&gt;
    {
        exception.FailureReason
            .Should().Be(PipelineFailure.BadAuthentication); <a id="CO6-3"></a><i class="conum" data-value="3"></i>
    }
);</pre>
</div>
<div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO6-1"><i class="conum" data-value="1"></i></a></p>
</td>
<td align="left" valign="top">
<p>First call results in a successful ping</p>
</td>
</tr>
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO6-2"><i class="conum" data-value="2"></i></a></p>
</td>
<td align="left" valign="top">
<p>Second call results in a bad response</p>
</td>
</tr>
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO6-3"><i class="conum" data-value="3"></i></a></p>
</td>
<td align="left" valign="top">
<p>The reason for the bad response is Bad Authentication</p>
</td>
</tr>
</table>
</div>
<p>When a bad authentication response occurs, the client does not attempt to deserialize the response body returned;
The response may or may not have a body and even when it does, it may not even be JSON.</p>
<p>In the following couple of examples, we set up a cluster that always returns a typical nginx HTML response body
with 401 response to client calls. In this first example, we assert that the failure is because of a 401 Bad Authentication
response but the response body is not captured on the response</p>
<div class="pre_wrapper lang-csharp">
<div class="console_code_copy" title="Copy to clipboard"></div>
<pre class="programlisting prettyprint lang-csharp">var audit = new Auditor(() =&gt; Framework.Cluster
    .Nodes(10)
    .Ping(r =&gt; r.SucceedAlways())
    .ClientCalls(r =&gt; r.FailAlways(401).ReturnResponse(HtmlNginx401Response)) <a id="CO7-1"></a><i class="conum" data-value="1"></i>
    .StaticConnectionPool()
    .AllDefaults()
);

audit = await audit.TraceElasticsearchException(
    new ClientCall {
        { AuditEvent.PingSuccess, 9200 },
        { AuditEvent.BadResponse, 9200 },
    },
    (e) =&gt;
    {
        e.FailureReason.Should().Be(PipelineFailure.BadAuthentication);
        e.Response.HttpStatusCode.Should().Be(401);
        e.Response.ResponseBodyInBytes.Should().BeNull(); <a id="CO7-2"></a><i class="conum" data-value="2"></i>
    }
);</pre>
</div>
<div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO7-1"><i class="conum" data-value="1"></i></a></p>
</td>
<td align="left" valign="top">
<p>Always return a 401 bad response with a HTML response on client calls</p>
</td>
</tr>
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO7-2"><i class="conum" data-value="2"></i></a></p>
</td>
<td align="left" valign="top">
<p>Assert that the response body bytes are null</p>
</td>
</tr>
</table>
</div>
<p>Now in this example, by turning on <code class="literal">DisableDirectStreaming()</code> on <code class="literal">ConnectionSettings</code>, we see the same behaviour exhibited
as before, but this time however, the response body bytes are captured in the response and can be inspected.</p>
<div class="pre_wrapper lang-csharp">
<div class="console_code_copy" title="Copy to clipboard"></div>
<pre class="programlisting prettyprint lang-csharp">var audit = new Auditor(() =&gt; Framework.Cluster
    .Nodes(10)
    .Ping(r =&gt; r.SucceedAlways())
    .ClientCalls(r =&gt; r.FailAlways(401).ReturnResponse(HtmlNginx401Response))
    .StaticConnectionPool()
    .Settings(s =&gt; s.DisableDirectStreaming())
);

audit = await audit.TraceElasticsearchException(
    new ClientCall {
        { AuditEvent.PingSuccess, 9200 },
        { AuditEvent.BadResponse, 9200 },
    },
    (e) =&gt;
    {
        e.FailureReason.Should().Be(PipelineFailure.BadAuthentication);
        e.Response.HttpStatusCode.Should().Be(401);
        e.Response.ResponseBodyInBytes.Should().NotBeNull(); <a id="CO8-1"></a><i class="conum" data-value="1"></i>
        var responseString = Encoding.UTF8.GetString(e.Response.ResponseBodyInBytes);
        responseString.Should().Contain("nginx/"); <a id="CO8-2"></a><i class="conum" data-value="2"></i>
        e.DebugInformation.Should().Contain("nginx/");
    }
);</pre>
</div>
<div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO8-1"><i class="conum" data-value="1"></i></a></p>
</td>
<td align="left" valign="top">
<p>Response bytes are set on the response</p>
</td>
</tr>
<tr>
<td align="left" valign="top" width="5%">
<p><a href="#CO8-2"><i class="conum" data-value="2"></i></a></p>
</td>
<td align="left" valign="top">
<p>Assert that the response contains <code class="literal">"nginx/"</code></p>
</td>
</tr>
</table>
</div>
</div>
</div>
</div><div class="navfooter">
<span class="prev">
<a href="unexpected-exceptions.html">« Unexpected exceptions</a>
</span>
<span class="next">
<a href="transports-and-pipelines.html">Transports and pipelines »</a>
</span>
</div>
</body>
</html>
